project:
  type: website

brand: tlm-styles/_brand.yml

resources:
  - "**/*.pdf"

website:
  title: "BIOL 346 An Ecological Perspective"
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: syllabus/index.qmd
        text: Syllabus
      - href: schedule/index.qmd
        text: Schedule

  sidebar:
    style: "docked"
    search: true
    contents: 
      - href: index.qmd
        text: Home
      - href: syllabus/index.qmd
      - href: schedule/index.qmd
      - href: lectures/index.qmd
      - href: module-1/index.qmd
        text: "Module 1: The Environment and Sustainability"
      - href: module-2/index.qmd
        text: "Module 2: Science, Matter, Energy, and Systems"
      - href: module-3/index.qmd
        text: "Module 3: Ecosystems: What are they and how do they work?"
      - href: module-4/index.qmd
        text: "Module 4: Human Population and Urbanization"
      - href: module-5/index.qmd
        text: "Module 5: Climate and Biodiversity: Saving Species and Ecosystems"	
      - href: module-6/index.qmd
        text: "Module 6: Food Production and the Environment	"
      - href: module-7/index.qmd
        text: "Module 7: Natural Resources"
      - href: module-8/index.qmd
        text: "Module 8: Air Pollution and Climate Change"
      - href: module-9/index.qmd
        text: "Module 9: Environmental Waste and Human Health"

format:
  html:
    toc: true
    theme: 
      - cosmo
      - brand
      - tlm-styles/tlm-theme.scss
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://use.typekit.net/tag1lvz.css">

execute:
  echo: false
  warning: false
  message: false